[project]
name = "attendance"
requires-python = ">=3.13"
version = "0.1"
dependencies = [
    "jinja2",
    "fastapi[standard]",
    "sqlmodel",
    "starlette",
    "itsdangerous",
    "python-dotenv",
    "requests>=2.32.3",
]
